name: CI

on: [push]

jobs:
    sast_scan:
      name: Run brakeman scan
      # Run this job on ubuntu-latest
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
        
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true
  
        - name: Run brakeman
          run: | 
            bundle exec brakeman -o .github/brakeman.log
            if grep -q "No warnings found" .github/brakeman.log; then
              echo "BRACKMAN_STATUS=Passed" >> $GITHUB_ENV
            else
              echo "BRACKMAN_STATUS=Failed" >> $GITHUB_ENV
            fi

        - name: Write log statuws to files
          uses: frdrwrt/write-to-file@v1.3
          with:
              filepath: .github/brakeman_status.json
              content: echo "${{ env.BRACKMAN_STATUS }}"
