name: CI

on: [push]

jobs:
    sast_scan:
      name: Run brakeman scan
      # Run this job on ubuntu-latest
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
        
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true
  
        - name: Run brakeman
          run: |
            output=$(bundle exec brakeman)
            echo "$output"
            if echo "$output" | grep -q "No warnings found"; then
              echo '{"status": "success"}' > status.json
            else
              echo '{"status": "failure"}' > status.json
            fi